# Generated by Django 5.2.8 on 2025-11-25 13:27

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_timeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='social_noti_recipie_318433_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeline',
            name='social_time_user_id_18cc11_idx',
        ),
        migrations.AlterField(
            model_name='timeline',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='social_noti_recipie_54eb87_idx'),
        ),
        migrations.AddIndex(
            model_name='timeline',
            index=models.Index(fields=['user', '-created_at'], name='social_time_user_id_886fb9_idx'),
        ),
    ]
